### ISSUE TITLE
I don't know why 180 ° should be added in the function getYaw().

### ISSUE THREAD

**Issue by printlin** [769484623/MahonyAHRSWithMPU9250#2]
in file MahonyAHRS.c line 182.
I found YAW data jump in the upper computer debugging. After searching, I found that you added 180 ° in getYaw().
thanks

**Comment by 769484623** [comment]
this project is a DEMO application of MahonyAHRS,which is an implementation of an algorithm paper, and the implementation (MahonyAHRS.c) is coded by [Madgwick](http://www.x-io.co.uk/open-source-imu-and-ahrs-algorithms/).

FYI

> https://ieeexplore.ieee.org/document/4608934?tp=&arnumber=4608934&url=http:%2F%2Fieeexplore.ieee.org%2Fstamp%2Fstamp.jsp%3Ftp%3D%26arnumber%3D4608934
